Import("*")

width = 32
rom0_length = 16<<10
bram0_length = 16<<10

rom_init = env.Command(
    "rom.init", 
    None, 
    f"ecpbram -w {int(width)} -d {int(rom0_length/width)} -g $TARGET"
)

env.Append(
)

