Import("*")

# @todo move address and length stuff to a file so we can add it as a source
width = 32
rom0_length = 16<<10
bram0_length = 16<<10

rom_init = env.Command(
    "rom.init", 
    None, 
    f"ecpbram -w {int(width)} -d {int(rom0_length/width)} -g $TARGET"
)

env.Append(
    VDEFINES = {
        "ROM0_LENGTH": rom0_length,
        "BRAM0_LENGTH": bram0_length
    }
)

soc_vvp = env.VVPFile("soc.vvp", "soc.v")
env.VVPRun(soc_vvp)
