Import("*")

sources = [
    "soc.v",
    "package/interconnect.v",
    "cores/bram.v",
    "cores/rom.v",
    neorv32_wrapper,
],

soc_base = env.Command(
    "ecp5_soc.json",
    sources,
    "yosys $YOSYSFLAGS -p '"+
    " read_verilog $VFLAGS $_VINCFLAGS $_VDEFFLAGS $SOURCE;" +
    " synth_ecp5 -json $TARGET" +
    "'"
)

Return("soc_base")
